# location /etc/metricbeat/

# Custom fields
metricbeat.modules:
- module: docker
  metricsets: ["cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s
- module: system
  metricsets:
    # CPU stats
    - cpu

    # System Load stats
    - load

    # Per CPU core stats
    #- core

    # IO stats
    #- diskio

    # Per filesystem stats
    - filesystem

    # File system summary stats
    - fsstat

    # Memory stats
    - memory

    # Network stats
    - network

    # Per process stats
    - process

    # Sockets (linux only)
    #- socket
  enabled: true
  period: 10s
  processes: ['.*']

logging:
    level: error
    #to_syslog: true
    to_files: true
    files:
      path: "/tmp/beats/logs"
      name: metricbeat_error.log
      rotateeverybytes: 2048
      keepfiles: 7
# Logstash output
