# location /etc/packetbeat/

# Custom fields
packetbeat.interfaces:
    device: any
packetbeat.flows:
    timeout: 30s
    period: 10s
packetbeat.protocols:
    icmp:
        enabled: true
    amqp:
        ports:
        - 5672
    dns:
        include_additionals: true
        include_authorities: true
        ports:
        - 53
    http:
        ports:
        - 80
        - 8080
        - 8000
        - 5000
        - 8002
    memcache:
        ports:
        - 11211
    mongodb:
        ports:
        - 27017
    mysql:
        ports:
        - 3306
    pgsql:
        ports:
        - 5432
    redis:
        ports:
        - 6379
    nfs:
        ports:
        - 2049
    thrift:
        ports:
        - 9090
# Logstash output
logging:
    level: error
    to_syslog: true
