version: "2"

services:
    eim-mysql:
        build: ./mysql
        hostname: eim-mysql
        stdin_open: true
        restart: always
        tty: true
        networks:
            - elastest
        ports:
            - "3306:3306"
        expose:
            - "3306"
    eim:
        build:  ./eim
        depends_on:
            - eim-mysql
            - sut
        links:
            - eim-mysql
        stdin_open: true
        tty: true
        environment:
            - KUBECONFIG=/tmp/ansible/beats/config
            - GOOGLE_APPLICATION_CREDENTIALS=/tmp/ansible/beats/gcp.json
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - ET_EDM_MYSQL_HOST=eim-mysql
            - ET_EDM_MYSQL_PORT=3306
            - WAIT_HOSTS=eim-mysql:3306
            - PASS=elastest
        expose:
            - 8080
            - 80
        ports:
            - 8080:8080
        hostname: eim
        networks:
            - elastest
    sut:
        image: elastest/eim-sut:latest
        user: root
        depends_on:
            - kibana
        stdin_open: true
        tty: true
        networks:
            - elastest
        cap_add:
            - ALL
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    elasticsearch:
        user: root
        #image: elastest/eim-elasticsearch:0.9.0
        image: elastest/eim-elasticsearch:latest
        ports:
                - "9200:9200"
                - "9300:9300"
        depends_on:
                - eim-mysql
        hostname: elasticsearch
        networks:
                - elastest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    logstash:
        #image: elastest/eim-logstash:0.9.0
        image: elastest/eim-logstash:latest
        user: root
        ports:
                - "5044:5044"
        depends_on: 
                - elasticsearch
        links:
                - elasticsearch
        hostname: logstash
        networks:
                - elastest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    kibana:
        #image: elastest/eim-kibana:0.9.0
        image: elastest/eim-kibana:latest
        ports: 
                - "5601:5601"
        depends_on:
                - logstash
        links:
                - elasticsearch
        hostname: kibana
        networks:
                - elastest
networks:
    elastest:
        driver: bridge

