version: '2'

services:
        eim-mongo:
                image: mvertes/alpine-mongo
                expose: 
                        - 27017
                ports: 
                        - "27017:27017"
                hostname: eim-mongo 
                stdin_open: true
                tty: true
                networks:
                        - elastest
        elasticsearch:
                image: elastest/eim-elasticsearch:0.5.0
                #image: elastest/eim-elasticsearch:latest
                ports:
                        - "9200:9200"
                        - "9300:9300"
                depends_on:
                        - eim-mongo
                hostname: elasticsearch
                networks:
                        - elastest
        logstash:
                image: elastest/eim-logstash:0.5.0
                #image: elastest/eim-logstash:latest
                ports:
                        - "5044:5044"
                depends_on: 
                        - elasticsearch
                links:
                        - elasticsearch
                hostname: logstash
                networks:
                        - elastest

        kibana:
                image: elastest/eim-kibana:0.5.0
                #image: elastest/eim-kibana:latest
                ports: 
                        - "5601:5601"
                depends_on:
                        - logstash
                links:
                        - elasticsearch
                hostname: kibana
                networks:
                        - elastest

        sut:
                image: elastest/eim-sut:0.5.0
                #image: elastest/eim-sut:latest
                #image: dev/sut-v3
#                volumes:
#                        - static-content:/tmp/ssh
                depends_on:
                        - kibana
                stdin_open: true
                tty: true
                #hostname: sut
                networks:
                        - elastest

        eim:
                image: elastest/eim:0.5.0
                #image: elastest/eim:latest
                # volumes:
                #       - static-content:/tmp/ssh 
                depends_on:
                        - sut
                        - eim-mongo
                links:
                        - eim-mongo
                stdin_open: true
                tty: true
                environment:
                        - ET_EIM_MONGO_HOST=eim-mongo
                expose:
                        - 8080
                ports:
                        - "8080:8080" 
                #hostname: eim
                networks:
                        - elastest

#volumes:
#        static-content:

networks:
        elastest:
                # external: true
                driver: bridge
