/**
 * Copyright (c) 2017 Atos
 * This program and the accompanying materials
 * are made available under the terms of the Apache License v2.0
 * which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *    @author David Rojo Antona (Atos)
 * 
 * OpenAPI spec version: 1.0.0
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * Developed in the context of ElasTest EU project http://elastest.io 
 */

package io.swagger.model;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class AgentConfigurationTest {
	
	@Test
	public void pojoTest() {
		
		AgentConfiguration agentCfg = new AgentConfiguration();
		agentCfg.setComponent("component");
		agentCfg.setExec("exec");
		AgentConfigurationPacketbeat packetbeat = new AgentConfigurationPacketbeat();
		agentCfg.setPacketbeat(packetbeat);
		AgentConfigurationTopbeat topbeat = new AgentConfigurationTopbeat();
		agentCfg.setTopbeat(topbeat);
		AgentConfigurationFilebeat filebeat = new AgentConfigurationFilebeat();
		agentCfg.setFilebeat(filebeat);
		
		assertEquals("component", agentCfg.getComponent());
		assertEquals("exec", agentCfg.getExec());
		assertEquals(filebeat, agentCfg.getFilebeat());
		assertEquals(topbeat, agentCfg.getTopbeat());
		assertEquals(packetbeat, agentCfg.getPacketbeat());
	}

}
