/**
 * Copyright (c) 2017 Atos
 * This program and the accompanying materials
 * are made available under the terms of the Apache License v2.0
 * which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *    @author David Rojo Antona (Atos)
 * 
 * OpenAPI spec version: 1.0.0
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * Developed in the context of ElasTest EU project http://elastest.io 
 */


package io.swagger.model;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

public class AgentConfigurationFilebeatTest {

	@Test
	public void pojoTest() {
		AgentConfigurationFilebeat agentCfgFilebeat = new AgentConfigurationFilebeat();
		agentCfgFilebeat.setStream("stream");
		List<String> paths = new ArrayList<String>();
		agentCfgFilebeat.setPaths(paths);
		
		assertEquals("stream", agentCfgFilebeat.getStream());
		assertEquals(paths, agentCfgFilebeat.getPaths());
	}
	
	@Test
	public void addPathTest() {
		AgentConfigurationFilebeat agentCfgFilebeat = new AgentConfigurationFilebeat();
		
		assertEquals(0, agentCfgFilebeat.getPaths().size());
		
		String path = "path";
		agentCfgFilebeat.addPathsItem(path);
		assertEquals(path, agentCfgFilebeat.getPaths().get(0));
	}
}
