/**
 * Copyright (c) 2017 Atos
 * This program and the accompanying materials
 * are made available under the terms of the Apache License v2.0
 * which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *    @author David Rojo Antona (Atos)
 * 
 * OpenAPI spec version: 1.0.0
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * Developed in the context of ElasTest EU project http://elastest.io 
 */

package io.swagger.model;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class HostTest {
	
	@Test
	public void pojoTest() {
		
		Host host = new Host();
		host.setAddress("172.21.0.5");
		host.setLogstashIp("172.21.0.4");
		host.setLogstashPort("1234");
		host.setUser("elastest");
		host.setPrivateKey("-----BEGIN RSA PRIVATE KEY-----\\nMIIEpAIBAAKCAQEAt7s9IdIBhoXqre2tXj2yHEVEhI0H/PApIcHteKTD3L2ogwhl\\nVOhI/hH6VhOXfEakGFQx/REiZg+nB5cD73oAqCHhCj04JJJjtwNfOJApnpiBh4Op\\nng/w+vL1vYByLPQhkGCLkMcya6aL++FuMJj9PSrWLEF8Lc7F1XbOKaMNVqZ667JD\\n4gjqWEWRfSiWefBrXbIf4NzLmzAt6ChdtQxqB3oZDUkH7hyj5amhkrQZlNxh7FVW\\niL6FtUQyXhT/Tj6mIe3krlSq68Hm9qSbtchYTww+NMtwp9hNLtwgzPGOdKIjGsHx\\nJh5ydngzKdeWzBjQDHWOdjO72gTobPHLvw8YbwIDAQABAoIBAQCXbgQ5nrvRIwjE\\nZ3OPi+wDrveFBDQEPfC4uPw/hhVEFzEPJllWPMkEVs7sKOOe8x4GS0aUHI4sblQt\\nRkNhGj32VU4EQWbHhbwXt/jARtl2tJ11koe3Fc55FsyBbp8r+965/0iof/VHkpIn\\nfKpz9XQq+OZivWpa2uRlRrEu0guJUPF1vX/RbNofoXu9G2xkBr/wHOPNzmk9WKik\\nfVfS/Li8RaDCHimsoPHIxrFueO1V+Gt8vD4e9TTjivg/0BmRfa0dX5lcHe6HSIQP\\nehIzutzmVFn9aCBGadCAD5ZHZaWeR9w6WCvsKS9udfJudcEP12LrDWqXfC2Cu9lP\\nq483RoK5AoGBAOM0n1y4CBu3kBkpqCJG2lq/dfJvVdXv3nunj5wWSl/ijkTtchCI\\nkcdzUOC0cizypUp0Fr3e0CthHBu/CaBkR5YTsbJB1mqRsUw5xGFfYbOFJAHIdXCp\\nndmT+D3PirDnfcPOBOgbLFic+UHMRG6GyUeQ8fgMSxPmGUgP9Xr/QzOlAoGBAM8E\\nJ/GBf81Zv1EZk2UgRR9xlL5X4//CtqHCKI3AFUBCTc1Fuh+Mz3Pt8aHLteAR5qDY\\njj44bM+WiGxCSs+WEQ9xqP8XqmL2etizeOVO9bIMd2ma8peRGRFG3BpZ5FxOvZTK\\n7HdZ7X3Pesvdgo15PQlLD7D89cPs4XNekbZMAQ+DAoGAWg7MsBq+FAZxlpe9bkC5\\nYkkLvlnFIzSd8lObh9oKBvGtRML9eHI5nl4mC7tamlhfjiBvtzjvOJKYaqMRdMLq\\n4SDTSX3xOHKhXT50icgd2OOIPzCu5EZHLCwLtKxkI/TOE+PAbCQBMuqdnigSY+EH\\nPVfFoXV1+OA22yqAOg2eHIUCgYAglFzc6y572OX9E3NY9O0r96obEqX1OGWZq37K\\nYDJ3/HdWGOUj1ftIGWhvuCmVa/vJ0IsCS8sEGIK71usDJHDm51JbYxQTowrOU+Bw\\n5i5QqRmZ6yLGq7UwPOCi3QbNaC753b29Qs/XfvGqZ+AF99CdR8zeY9Eh1oPcrkNs\\nVyXLlQKBgQCVtDGPiiVI1cfexJj3+txO11AvQEOD8udyc5TmSBc/GGeaz74Lhb7H\\nJ1wqH2kAifyb5MZaQBvw8Z7oKSPFuYWRJ35YZQ6UbiE6bAp+inY0NBbR3YWNhh+F\\n6yCgQarAypnJd5/p69IrRGM+BF/Xy4nk5IgG+RNcu2DTjFFWyCkmBA==\\n-----END RSA PRIVATE KEY-----");
			
		assertEquals("172.21.0.5", host.getAddress());
		assertEquals("172.21.0.4", host.getLogstashIp());
		assertEquals("1234", host.getLogstashPort());
		assertEquals("elastest", host.getUser());
		assertEquals("-----BEGIN RSA PRIVATE KEY-----\\nMIIEpAIBAAKCAQEAt7s9IdIBhoXqre2tXj2yHEVEhI0H/PApIcHteKTD3L2ogwhl\\nVOhI/hH6VhOXfEakGFQx/REiZg+nB5cD73oAqCHhCj04JJJjtwNfOJApnpiBh4Op\\nng/w+vL1vYByLPQhkGCLkMcya6aL++FuMJj9PSrWLEF8Lc7F1XbOKaMNVqZ667JD\\n4gjqWEWRfSiWefBrXbIf4NzLmzAt6ChdtQxqB3oZDUkH7hyj5amhkrQZlNxh7FVW\\niL6FtUQyXhT/Tj6mIe3krlSq68Hm9qSbtchYTww+NMtwp9hNLtwgzPGOdKIjGsHx\\nJh5ydngzKdeWzBjQDHWOdjO72gTobPHLvw8YbwIDAQABAoIBAQCXbgQ5nrvRIwjE\\nZ3OPi+wDrveFBDQEPfC4uPw/hhVEFzEPJllWPMkEVs7sKOOe8x4GS0aUHI4sblQt\\nRkNhGj32VU4EQWbHhbwXt/jARtl2tJ11koe3Fc55FsyBbp8r+965/0iof/VHkpIn\\nfKpz9XQq+OZivWpa2uRlRrEu0guJUPF1vX/RbNofoXu9G2xkBr/wHOPNzmk9WKik\\nfVfS/Li8RaDCHimsoPHIxrFueO1V+Gt8vD4e9TTjivg/0BmRfa0dX5lcHe6HSIQP\\nehIzutzmVFn9aCBGadCAD5ZHZaWeR9w6WCvsKS9udfJudcEP12LrDWqXfC2Cu9lP\\nq483RoK5AoGBAOM0n1y4CBu3kBkpqCJG2lq/dfJvVdXv3nunj5wWSl/ijkTtchCI\\nkcdzUOC0cizypUp0Fr3e0CthHBu/CaBkR5YTsbJB1mqRsUw5xGFfYbOFJAHIdXCp\\nndmT+D3PirDnfcPOBOgbLFic+UHMRG6GyUeQ8fgMSxPmGUgP9Xr/QzOlAoGBAM8E\\nJ/GBf81Zv1EZk2UgRR9xlL5X4//CtqHCKI3AFUBCTc1Fuh+Mz3Pt8aHLteAR5qDY\\njj44bM+WiGxCSs+WEQ9xqP8XqmL2etizeOVO9bIMd2ma8peRGRFG3BpZ5FxOvZTK\\n7HdZ7X3Pesvdgo15PQlLD7D89cPs4XNekbZMAQ+DAoGAWg7MsBq+FAZxlpe9bkC5\\nYkkLvlnFIzSd8lObh9oKBvGtRML9eHI5nl4mC7tamlhfjiBvtzjvOJKYaqMRdMLq\\n4SDTSX3xOHKhXT50icgd2OOIPzCu5EZHLCwLtKxkI/TOE+PAbCQBMuqdnigSY+EH\\nPVfFoXV1+OA22yqAOg2eHIUCgYAglFzc6y572OX9E3NY9O0r96obEqX1OGWZq37K\\nYDJ3/HdWGOUj1ftIGWhvuCmVa/vJ0IsCS8sEGIK71usDJHDm51JbYxQTowrOU+Bw\\n5i5QqRmZ6yLGq7UwPOCi3QbNaC753b29Qs/XfvGqZ+AF99CdR8zeY9Eh1oPcrkNs\\nVyXLlQKBgQCVtDGPiiVI1cfexJj3+txO11AvQEOD8udyc5TmSBc/GGeaz74Lhb7H\\nJ1wqH2kAifyb5MZaQBvw8Z7oKSPFuYWRJ35YZQ6UbiE6bAp+inY0NBbR3YWNhh+F\\n6yCgQarAypnJd5/p69IrRGM+BF/Xy4nk5IgG+RNcu2DTjFFWyCkmBA==\\n-----END RSA PRIVATE KEY-----"
				, host.getPrivateKey());
	}
}
