/**
 * Copyright (c) 2019 Atos
 * This program and the accompanying materials
 * are made available under the terms of the Apache License v2.0
 * which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *    @author Fernando Mendez Requena - fernando.mendez@atos.net
 * 
 * OpenAPI spec version: 1.0.0
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * Developed in the context of ElasTest EU project http://elastest.io 
 */

package io.elastest.eim.test.e2e;

import java.util.Collections;


import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import com.fasterxml.jackson.databind.util.JSONPObject;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class EimApiRestTest {

	private String private_key = System.getProperty("privateKey");
	private String sut_address = System.getProperty("ipAddr");
	private String server = "http://nightly.elastest.io:37004/eim/api/agent/";
	private String user = "root";
	
	// public RestClient client = new RestClient(server, user, password,
	// secureElastest);

	public RestTemplate restTemplate = new RestTemplate();
	public HttpHeaders headers = new HttpHeaders();

	// TODO - registerAgent_then200OK()
	@Test
	public void registerAgentTest() {

		// Remove "\" last character
		String privateKey_modified = private_key.substring(0, private_key.length() - 1).replaceAll("\\s","");
		
		String payload = "{\"address\":\""+sut_address+"\",\"user\":\""+user+"\",\"private_key\":\""+privateKey_modified+"\",\"logstash_ip\":\"172.20.0.4\",\"logstash_port\":\"5044\",\"password\":\"elastest\"}";
		
		JsonObject jsonObject = new JsonParser().parse(payload).getAsJsonObject();
		
		String URL = server;
		System.out.println("Endpoint request " + URL);
		System.out.println("Json: " + jsonObject);
		System.out.println("Json to String: " + jsonObject.toString());

		headers.setContentType(MediaType.APPLICATION_JSON);
		headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));

		HttpEntity<String> request = new HttpEntity<String>(jsonObject.toString(), headers);
		System.out.println("This is the request: "+request.toString());
		
		ResponseEntity<String> response = restTemplate.exchange(URL,  HttpMethod.POST, request, String.class);
		
		System.out.println("Response for Test1: "+response);

		Assertions.assertEquals(200, response.getStatusCodeValue());
		
		
	}

	/*
	 * // TODO - request_packetloss_action_then200OK
	 *//**
		 * curl -i -X POST -H "Content-Type:application/json" -H
		 * "Accept:application/json"
		 * http://localhost:8080/eim/api/agent/controllability/iagent0/packetloss -d '{
		 * "exec": "EXECBEAT", "component": "EIM", "packetLoss": "0.01", "stressNg": "",
		 * "dockerized": "yes", "cronExpression": "@every 60s" }'
		 */
	/*
	 * 
	 * @Test public void requestActionPacketLossTest() { String
	 * uri_packetloss_action = "controllability/iagent0/packetloss"; // String
	 * payload = //
	 * "{\"exec\":\"EXECBEAT\",\"component\":\"EIM\",\"packetLoss\":\"0.01\",\"stressNg\":\"\",\"dockerized\":\"yes\",\"cronExpression\":\"
	 * @every // 60s\"}";
	 * 
	 * Map<String, String> body = new HashMap<>(); body.put("exec", "EXECBEAT");
	 * body.put("component", "EIM"); body.put("packetLoss", "0.01");
	 * body.put("stressNg", ""); body.put("dockerized", "yes");
	 * body.put("cronExpression", "@every 60s");
	 * 
	 * String URL = server + uri_packetloss_action;
	 * 
	 * System.out.println("Endpoint request " + server + uri_packetloss_action);
	 * System.out.println("Payload:" + body);
	 * 
	 * headers.setContentType(MediaType.APPLICATION_JSON);
	 * headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
	 * 
	 * HttpEntity<Map<String, String>> request = new HttpEntity<Map<String,
	 * String>>(body, headers);
	 * 
	 * Assertions.assertEquals(200, restTemplate.exchange(URL, HttpMethod.POST,
	 * request, Map.class).getStatusCodeValue());
	 * 
	 * }
	 * 
	 * // TODO - request_stress_action_then200OK()
	 * 
	 *//**
		 * curl -i -X POST -H "Content-Type:application/json" -H
		 * "Accept:application/json"
		 * http://localhost:8080/eim/api/agent/controllability/iagent0/stress -d '{
		 * "exec": "EXECBEAT", "component": "EIM", "packetLoss": "", "stressNg": "4",
		 * "dockerized": "yes", "cronExpression": "@every 60s" }'
		 **/
	/*
	 * 
	 * @Test public void requestActionStressTest() { String uri_stress_action =
	 * "controllability/iagent0/stress"; // String payload = //
	 * "{\"exec\":\"EXECBEAT\",\"component\":\"EIM\",\"packetLoss\":\"\",\"stressNg\":\"4\",\"dockerized\":\"yes\",\"cronExpression\":\"
	 * @every // 60s\"}"; Map<String, String> body = new HashMap<>();
	 * body.put("exec", "EXECBEAT"); body.put("component", "EIM");
	 * body.put("packetLoss", ""); body.put("stressNg", "4"); body.put("dockerized",
	 * "yes"); body.put("cronExpression", "@every 60s");
	 * 
	 * String URL = server + uri_stress_action;
	 * 
	 * System.out.println("Endpoint request: " + URL);
	 * System.out.println("Payload: " + body);
	 * 
	 * headers.setContentType(MediaType.APPLICATION_JSON);
	 * headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
	 * 
	 * HttpEntity<Map<String, String>> request = new HttpEntity<Map<String,
	 * String>>(body, headers); Assertions.assertEquals(200,
	 * restTemplate.exchange(URL, HttpMethod.POST, request,
	 * Map.class).getStatusCodeValue()); }
	 * 
	 * // TODO - Unistall Agent - request_unistall_agent
	 * 
	 *//**
		 * curl -i -X DELETE -H "Content-Type:application/json" -H
		 * "Accept:application/json"
		 * http://localhost:8080/eim/api/agent/iagent0/unmonitor
		 * 
		 * @throws InterruptedException
		 */
	/*
	 * 
	 * @Test public void requestUnistallAgentTest() throws InterruptedException {
	 * String uri_unistall_agent = "iagent0/unmonitor"; TimeUnit.SECONDS.sleep(160);
	 * 
	 * headers.setContentType(MediaType.APPLICATION_JSON);
	 * headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
	 * 
	 * Map<String, String> body = new HashMap<>(); String URL = server +
	 * uri_unistall_agent;
	 * 
	 * System.out.println("Endpoint request: " + URL);
	 * 
	 * HttpEntity<Map<String, String>> request = new HttpEntity<Map<String,
	 * String>>(body, headers);
	 * 
	 * Assertions.assertEquals(200, restTemplate.exchange(URL, HttpMethod.DELETE,
	 * request, Map.class).getStatusCodeValue());
	 * 
	 * }
	 * 
	 * // TODO - Remove Agent
	 * 
	 *//**
		 * curl -i -X DELETE -H "Content-Type:application/json" -H
		 * "Accept:application/json" http://localhost:8080/eim/api/agent/iagent0
		 * 
		 * @throws InterruptedException
		 *//*
			 * 
			 * @Test public void requestDeleteAgentTest() throws InterruptedException {
			 * String uri_delete_agent = "iagent0"; TimeUnit.SECONDS.sleep(160);
			 * 
			 * Map<String, String> body = new HashMap<>(); String URL = server +
			 * uri_delete_agent;
			 * 
			 * System.out.println("Endpoint request: " + URL);
			 * 
			 * HttpEntity<Map<String, String>> request = new HttpEntity<Map<String,
			 * String>>(body, headers); Assertions.assertEquals(200,
			 * restTemplate.exchange(URL, HttpMethod.DELETE, request,
			 * Map.class).getStatusCodeValue());
			 * 
			 * }
			 */

}
