/**
 * Copyright (c) 2019 Atos
 * This program and the accompanying materials
 * are made available under the terms of the Apache License v2.0
 * which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *    @author Fernando Mendez Requena - fernando.mendez@atos.net
 * 
 * OpenAPI spec version: 1.0.0
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * Developed in the context of ElasTest EU project http://elastest.io 
 */

package io.elastest.eim.test.e2e;

import static java.lang.invoke.MethodHandles.lookup;
import static org.slf4j.LoggerFactory.getLogger;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.slf4j.Logger;

import io.elastest.eim.test.base.EimBaseTest;
import io.github.bonigarcia.seljup.BrowserType;
import io.github.bonigarcia.seljup.DockerBrowser;
import io.github.bonigarcia.seljup.SeleniumExtension;

/**
 * Check that the EMS works properly together with a TJob.
 */
@Tag("e2e")
@DisplayName("E2E tests of EIM through TORM")
@ExtendWith(SeleniumExtension.class)

public class EimTJobE2eTest extends EimBaseTest {
	
	private String sutName = "EIMe2eSut";
	final int timeOut  = 800;
	private String sut_ip = System.getenv("ET_SUT_HOST");
	

	final Logger log = getLogger(lookup().lookupClass());
	String projectName = "EIMe2e";

	private static final Map<String, List<String>> tssMap;
	static {
		tssMap = new HashMap<String, List<String>>();
		tssMap.put("EIM", null);
	}
	
	
	
	

	void createProject(WebDriver driver) throws Exception {
		navigateToTorm(driver);
		if (!etProjectExists(driver, projectName)) {
			createNewETProject(driver, projectName);
		}
	}

	void createProjectAndSut(WebDriver driver) throws Exception {
		navigateToTorm(driver);

		if (!etProjectExists(driver, projectName)) {
			createNewETProject(driver, projectName);
		}
		if (!etSutExistsIntoProject(driver, projectName, sutName)) {

			// Create SuT
			String sutDesc = "SuT for E2E test";
			String sutImage = "elastest/eim-sut:latest";

			createNewSutDeployedByElastestWithImage(driver, sutName, sutDesc, sutImage, null, null, false);
			
			
			
		}

	}
	
	@Test
	@DisplayName("EIM in a TJob")
		void testTJob(@DockerBrowser(type = BrowserType.CHROME) RemoteWebDriver localDriver, TestInfo testInfo) throws Exception {
		setupTestBrowser(testInfo, BrowserType.CHROME, localDriver);

		// Setting up the TJob used in the test
		this.createProjectAndSut(driver);
		navigateToETProject(driver, projectName);
		String tJobName = "EIM e2e tjob";
		if (!etTJobExistsIntoProject(driver, projectName, tJobName)) {

			String tJobTestResultPath = "/elastest-instrumentation-manager";
			String tJobImage = "elastest/test-etm-alpinegitjava";
			
			String privateKey = "\"-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAu3j8Zep/0/XHa2Bld1LntS0HtQolkd8Rqcwd41ZTaMjdlORh\nu7ppMNhAUAbG+lzNEdBP+WSIE/WX71FA0kSs3UnCJomDDnHQWjkvFvoVyRpBxQ6P\ndkiRfRi9Q10oMZmkfjP0V/+FU3ICEOiXJtwhmzLF0tHHYfrhLNU59s1L7I1E15Zt\nTVB1HE3V1gPymJO19AhDJMz5CRXvJR0QLcSo1Ej7FgAE3eePPOjOxZQ3pc9FEnGl\nHTM2zRAOIbqdXWkdtnevmP7PgNOg//rdnT1+WMOTSIZgIXX6DiwrBJSzG541F5JM\n1nlgzHDzUeB9iY4w8EE+h8aM3mBInKkfNVZ43QIDAQABAoIBACX8/igovH5W73Hy\ntpzXT9yGo2ksBTDp4splcij+9Sfmi///x04jF+2t5FpTBT72Txes/oeqt2hT+9Wi\nwV/aSq0MpSrp8oSay3182O3u/zsg9vLXYHq3ecO/n5pm5h4m5A4uuPSb8ohWMdT7\nTKWzNZwdTbjKiXxxOe+7xWMddqUYIbWXVo2i9TpB9gX4U46kgSdvnz3uoRO0amGB\nZ7jW5oLzfux2nm5V2Yt0PeKobAzn4mh4Bi9g1uXNHjKgys6+7MgRWQBEp0LyCXSC\nQ4B6dZ2eGQWj+H7HUt/SDSa+GC/q+aKMCViRKe6wEZYIzOb+eDCX0rySJoLkp44T\nACoHKIECgYEA+SyoJPbR87MOerkG/NXA/Q6T8DvX+nxuybz0O1ElLAvUiag+WoBw\npVHPHpeMp7/N79YHqhWTu87UMZOfxaR3BOfZNbUc7MgETp5O4zA5AL5RvJxI+MBt\nnhZTRbT6BQ12WhWVQChd/krDhGCY4lJ1GudGReGtUDLtn3LzT2Ku3l8CgYEAwJuk\npCe8wQCMxHHW1siHKO+eJGI2ZsFKCTmq0AmuTgUF/NdxQ0CymRVl/+5e364aVE3L\nKcTdqb88Zr0Bmbx1k23OkjmsErDrdWqy6vOIsPS+grTvGPvesFdd45lpWeQl0hxn\nidDB5A00haYhTc1k+fxVlix7Qm7Hlku+LGkHekMCgYAN+uhwMnzzHF+6mPkAZInQ\naOn595GVlzesD/LwBQx93SgOlSbycvRfAikJwVz96HAIfcyuSUmhpugW4/5521Fm\nMA/qyH+X9VzwgEdSzdjU5ti1KVuawUklLoF7jrzcXbX/NejK0bj8VHuFyNmrEQ9K\n9CDoONI9hq34XT2zfYjsJwKBgDn536ol5/Q0hSrQlXmbbMvOrMyI35U4k1+JgzgR\n4ezMKEw+UXKL8/aOcWCDUP2Fe5lqvT+6aXqh/L10IRo0lzOkduye/YO2y3lRf7+n\nRLr3QK05Z0se7Z4o/jL3R7XuLdA8CpJ6SxKpQukD47x2mfGBmgWVKBkMHXnJHNpj\nVwPfAoGBANtqpHU8lWUI2Ex0IR0SlRKK8XC7OGvRVnpkX3cBfuGNN8iJaPFz/17+\nLfPVxdtNS2l+cq2vLJCma4GvrXZCuV4Gm0H1Gp5FIheFsns82cxARatHnf5rTjEh\ncAGCP+fTE6+8yR1zok7nRKpo3172KMw1vRfutPws/y68mBq7EBxO\n-----END RSA PRIVATE KEY-----\"";
			String SUT_IP = "\""+sut_ip+"\"";
						
			String commands = "git clone https://github.com/elastest/elastest-instrumentation-manager.git; "
					+ "cd elastest-instrumentation-manager/e2e-test/; "
					+ "mvn package -DskipTests=true; "
					+ "mvn test -Dtest=io.elastest.eim.test.e2e.EimApiRestTest -DargLine='-Dprivate_key="+privateKey+" -Dsut_address="+SUT_IP+"'; "
					+ "exit";
			
			System.out.println("Commands: "+commands);
			
			createNewTJob(driver, tJobName, tJobTestResultPath, sutName, tJobImage, false, commands, null, null, null,null);
			
		}
		// Run the TJob
		runTJobFromProjectPage(driver, tJobName);
		this.checkFinishTJobExec(driver, timeOut, "SUCCESS", false);
	}

}
