version: '3'

services:
         eim-mysql:
                image: elastest/eim-mysql-dev
                expose: 
                        - 52000
                ports: 
                        - "52000:3306"
                hostname: eim-mysql 
                stdin_open: true
                tty: true
                networks:
                        - elastest
         sut:
                image: elastest/eim-sut:latest
                depends_on:
                        - eim-mysql
                stdin_open: true
                tty: true
                #hostname: sut
                networks:
                        - elastest
         eim:
                image: elastest/eim-dev
                depends_on:
                        - eim-mysql
                links:
                        - eim-mysql
                stdin_open: true
                tty: true
                environment:
                        - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
                        - ET_EDM_MYSQL_HOST=eim-mysql
                        - ET_EDM_MYSQL_PORT=52000
                        - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
                        - ET_EDM_API=http://edm:37003/
                        - ET_EPM_API=http://epm:37002/
                        - ET_ETM_API=http://etm:37006/
                        - ET_ESM_API=http://esm:37005/
                        - ET_EIM_API=http://eim:37004/
                        - ET_ETM_LSBEATS_HOST=etm-beats
                        - ET_ETM_LSBEATS_PORT=5044
                        - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
                        - ET_ETM_RABBIT_HOST=etm-rabbitmq
                        - ET_ETM_RABBIT_PORT=5672
                        - ET_EMP_API=http://eim:37001/
                        - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
                        - ET_EMP_INFLUXDB_HOST=emp-influxdb
                        - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
                ports:
                        - "37004:8080" 
                networks:
                        - elastest

networks:
        elastest:
                driver: bridge
