---
#This playbook delete the ssh key from root user of the authorized_keys file in the .ssh directory of the user in SuT
- name: ssh-key-delete
  hosts: ##targethost## 
  remote_user: ##user##

  tasks:
          - name: delete ssh-key from authorized_keys file of the user
            authorized_key:
              user: ##user## 
              state: absent
              key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

