---
# file: playbook-delete-beats-output-logstash-template.yml

- hosts: ##targethost##
  vars:
    AGENT_ID: ##targethost##
  remote_user: ##user##
  become: yes
  tasks:

  - name: Check if Service Exists packebeat
    stat: path=/etc/init.d/packetbeat
    register: service_status

  - name: Stop service packetbeat
    service: name=packetbeat state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: Check if Service Exists metricbeat
    stat: path=/etc/init.d/metricbeat
    register: service_status

  - name: Stop service metricbeats
    service: name=metricbeat state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: Check if Service Exists filebeat
    stat: path=/etc/init.d/filebeat
    register: service_status

  - name: Stop service filebeat
    service: name=filebeat state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: Check if Service Exists execbeat
    stat: path=/etc/init.d/execbeat
    register: service_status_execbeat

  - name: Stop service execbeat
    service: name=execbeat state=stopped
    when: service_status_execbeat.stat.exists == true
    register: service_execbeat

  - name: "Remove execbeat dependencies"
    file:
      path: /etc/execbeat/
      state: absent
    when: service_status_execbeat.stat.exists == true

  - name: Check if iptables list is not empty
    command: sudo iptables --list --line-numbers
    register: iptables_lists_exists
  
  - name: "Restore default iptables rules of SUT"
    shell: sudo iptables -D {{ item }}
    with_items: 
      -  "##item##"
    when: iptables_lists_exists!="0"

  - name: remove packetbeat
    apt:
      name: packetbeat
      state: absent
    when: service_status.stat.exists

  - name: remove metricbeat
    apt:
      name: metricbeat
      state: absent
    when: service_status.stat.exists

  - name: remove filebeat
    apt:
      name: filebeat
      state: absent
    when: service_status.stat.exists

# pending to delete also folder and conf files of each beat located in /etc/<beat_name>
