---
# file: playbook-delete-beats-output-logstash-template.yml

- hosts: ##targethost##
  remote_user: elastest
  become: yes
  tasks:
   - name: remove packetbeat
     apt:
       name: packetbeat
       state: absent
   - name: remove metricbeat
     apt:
       name: metricbeat
       state: absent
   - name: remove filebeat
     apt:
       name: filebeat
       state: absent
