apiVersion: v1
kind: Service
metadata:
  name: eim-sut
  labels:
    app: elastest
    elastest-component: eim-sut
    io.elastest.service: eim-sut
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 5000  
  selector:
    elastest-service: eim-sut
  type: NodePort
status:
  loadBalancer: {}