---
- hosts: iagent1
  remote_user: elastest
  become: yes
  tasks:
   - name: remove packetbeat
     apt:
       name: packetbeat
       state: absent
   - name: remove topbeat
     apt:
       name: topbeat
       state: absent
   - name: remove filebeat
     apt:
       name: filebeat
       state: absent
